/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyExpenseRouteImport } from './routes/daily-expense'
import { Route as DividendsRouteImport } from './routes/dividends'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ApiCrudRouteImport } from './routes/api/crud'
import { Route as ApiStocksRouteImport } from './routes/api/stocks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyExpenseRoute = DailyExpenseRouteImport.update({
  id: '/daily-expense',
  path: '/daily-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const DividendsRoute = DividendsRouteImport.update({
  id: '/dividends',
  path: '/dividends',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrudRoute = ApiCrudRouteImport.update({
  id: '/api/crud',
  path: '/api/crud',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksRoute = ApiStocksRouteImport.update({
  id: '/api/stocks',
  path: '/api/stocks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-expense': typeof DailyExpenseRoute
  '/dividends': typeof DividendsRoute
  '/ledger': typeof LedgerRoute
  '/stocks': typeof StocksRoute
  '/transactions': typeof TransactionsRoute
  '/api/crud': typeof ApiCrudRoute
  '/api/stocks': typeof ApiStocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-expense': typeof DailyExpenseRoute
  '/dividends': typeof DividendsRoute
  '/ledger': typeof LedgerRoute
  '/stocks': typeof StocksRoute
  '/transactions': typeof TransactionsRoute
  '/api/crud': typeof ApiCrudRoute
  '/api/stocks': typeof ApiStocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-expense': typeof DailyExpenseRoute
  '/dividends': typeof DividendsRoute
  '/ledger': typeof LedgerRoute
  '/stocks': typeof StocksRoute
  '/transactions': typeof TransactionsRoute
  '/api/crud': typeof ApiCrudRoute
  '/api/stocks': typeof ApiStocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-expense'
    | '/dividends'
    | '/ledger'
    | '/stocks'
    | '/transactions'
    | '/api/crud'
    | '/api/stocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily-expense'
    | '/dividends'
    | '/ledger'
    | '/stocks'
    | '/transactions'
    | '/api/crud'
    | '/api/stocks'
  id:
    | '__root__'
    | '/'
    | '/daily-expense'
    | '/dividends'
    | '/ledger'
    | '/stocks'
    | '/transactions'
    | '/api/crud'
    | '/api/stocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyExpenseRoute: typeof DailyExpenseRoute
  DividendsRoute: typeof DividendsRoute
  LedgerRoute: typeof LedgerRoute
  StocksRoute: typeof StocksRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiCrudRoute: typeof ApiCrudRoute
  ApiStocksRoute: typeof ApiStocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-expense': {
      id: '/daily-expense'
      path: '/daily-expense'
      fullPath: '/daily-expense'
      preLoaderRoute: typeof DailyExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividends': {
      id: '/dividends'
      path: '/dividends'
      fullPath: '/dividends'
      preLoaderRoute: typeof DividendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crud': {
      id: '/api/crud'
      path: '/api/crud'
      fullPath: '/api/crud'
      preLoaderRoute: typeof ApiCrudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks': {
      id: '/api/stocks'
      path: '/api/stocks'
      fullPath: '/api/stocks'
      preLoaderRoute: typeof ApiStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyExpenseRoute: DailyExpenseRoute,
  DividendsRoute: DividendsRoute,
  LedgerRoute: LedgerRoute,
  StocksRoute: StocksRoute,
  TransactionsRoute: TransactionsRoute,
  ApiCrudRoute: ApiCrudRoute,
  ApiStocksRoute: ApiStocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
